import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

type Lang = 'ru' | 'en' | 'es' | 'de' | 'fr' | 'zh';

// Словарь RU→EN для эмоций (уникальные ключи). Остальные языки копируют EN как базу.
const RU_EN: Record<string, string> = {
  // anger/shame/sadness/fear/joy уникальные
  Холодность: 'Coldness',
  Злость: 'Anger',
  Бешенство: 'Fury',
  Сарказм: 'Sarcasm',
  Раздражение: 'Irritation',
  Ярость: 'Rage',
  Унижение: 'Humiliation',
  Обида: 'Hurt',
  Ненависть: 'Hatred',
  Нетерпение: 'Impatience',
  Отвращение: 'Disgust',
  Надменность: 'Arrogance',
  Злорадство: 'Schadenfreude',
  Недовольство: 'Discontent',
  Цинизм: 'Cynicism',
  Протест: 'Protest',
  Неистовость: 'Frenzy',
  Враждебность: 'Hostility',
  Равнодушие: 'Indifference',
  Безучастность: 'Aloofness',
  Неприязнь: 'Dislike',
  Пренебрежение: 'Contempt',
  Зависть: 'Envy',
  Мстительность: 'Vengefulness',
  Высокомерие: 'Haughtiness',

  Вина: 'Guilt',
  Раскаяние: 'Remorse',
  Нечестность: 'Dishonesty',
  'Угрызение совести': 'Compunction',
  Стеснение: 'Shyness',
  Неловкость: 'Awkwardness',
  Похоть: 'Lust',
  Ущербность: 'Inferiority',
  Растерянность: 'Confusion',
  Обман: 'Deceit',
  'Потеря лица': 'Loss of face',
  Смущение: 'Embarrassment',
  Позор: 'Disgrace',
  Сожаление: 'Regret',
  Расщепление: 'Splitting',
  Озабоченность: 'Preoccupation',
  Брошенность: 'Abandonment',
  Замкнутость: 'Withdrawal',
  Угрюмость: 'Sullenness',
  Угнетённость: 'Dejection',
  Пассивность: 'Passivity',
  Отвержение: 'Rejection',

  Огорчение: 'Upset',
  Горе: 'Grief',
  Боль: 'Pain',
  Одиночество: 'Loneliness',
  Отчуждение: 'Alienation',
  Разочарование: 'Disappointment',
  Поражение: 'Defeat',
  'Жалость к себе': 'Self-pity',
  Тоска: 'Yearning',
  Подавленность: 'Depression',
  Предательство: 'Betrayal',
  Скука: 'Boredom',
  Печаль: 'Sadness',
  Апатия: 'Apathy',
  Примирение: 'Resignation',
  Скорбь: 'Sorrow',
  Отчаяние: 'Despair',
  Ущемлённость: 'Feeling slighted',

  Волнение: 'Agitation',
  Испуг: 'Fright',
  Паника: 'Panic',
  Беспокойство: 'Worry',
  Неуверенность: 'Insecurity',
  Боязливость: 'Timidity',
  Подозрительность: 'Suspicion',
  Трусость: 'Cowardice',
  Нерешительность: 'Indecision',
  Настороженность: 'Wariness',
  Смятение: 'Confusion',
  Тревога: 'Anxiety',
  Ужас: 'Terror',
  Опасение: 'Apprehension',
  Робость: 'Bashfulness',
  Застенчивость: 'Shyness',
  Безнадёжность: 'Hopelessness',
  Сдержанность: 'Reserve',
  Скрытность: 'Secretiveness',
  Скованность: 'Constraint',
  Замешательство: 'Perplexity',
  Ошарашенность: 'Stunned',
  Озадаченность: 'Puzzlement',

  Благодарность: 'Gratitude',
  Доверие: 'Trust',
  Воодушевление: 'Inspiration',
  Озарение: 'Insight',
  Сопричастность: 'Belonging',
  Умиротворение: 'Serenity',
  Радушие: 'Warmth',
  Единство: 'Unity',
  Торжественность: 'Solemnity',
  Наслаждение: 'Pleasure',
  Общность: 'Community',
  Восторг: 'Delight',
  Благодать: 'Grace',
  Поддержка: 'Support',
  Веселье: 'Merriment',
  Надежда: 'Hope',
  Уверенность: 'Confidence',
  Лёгкость: 'Lightness',
  Любовь: 'Love',
  Удовлетворение: 'Satisfaction',
  Облегчение: 'Relief',
  Обожание: 'Adoration',
  Преклонение: 'Reverence',
  'Подъём духа': 'Uplift',
  Энтузиазм: 'Enthusiasm',
};

// RU→ES
const RU_ES: Record<string, string> = {
  Холодность: 'Frialdad',
  Злость: 'Enojo',
  Бешенство: 'Furia',
  Сарказм: 'Sarcasmo',
  Раздражение: 'Irritación',
  Ярость: 'Rabia',
  Унижение: 'Humillación',
  Обида: 'Ofensa',
  Ненависть: 'Odio',
  Нетерпение: 'Impaciencia',
  Отвращение: 'Asco',
  Надменность: 'Arrogancia',
  Злорадство: 'Regodeo',
  Недовольство: 'Descontento',
  Цинизм: 'Cinismo',
  Протест: 'Protesta',
  Неистовость: 'Frenesí',
  Враждебность: 'Hostilidad',
  Равнодушие: 'Indiferencia',
  Безучастность: 'Desapego',
  Неприязнь: 'Antipatía',
  Пренебрежение: 'Desprecio',
  Зависть: 'Envidia',
  Мстительность: 'Venganza',
  Высокомерие: 'Soberbia',

  Вина: 'Culpa',
  Раскаяние: 'Remordimiento',
  Нечестность: 'Deshonestidad',
  'Угрызение совести': 'Remordimiento',
  Стеснение: 'Timidez',
  Неловкость: 'Torpeza',
  Похоть: 'Lujuria',
  Ущербность: 'Inferioridad',
  Растерянность: 'Confusión',
  Обман: 'Engaño',
  'Потеря лица': 'Pérdida de reputación',
  Смущение: 'Vergüenza',
  Позор: 'Deshonra',
  Сожаление: 'Arrepentimiento',
  Расщепление: 'Escisión',
  Озабоченность: 'Preocupación',
  Брошенность: 'Abandono',
  Замкнутость: 'Aislamiento',
  Угрюмость: 'Malhumor',
  Угнетённость: 'Abatimiento',
  Пассивность: 'Pasividad',
  Отвержение: 'Rechazo',

  Огорчение: 'Disgusto',
  Горе: 'Duelo',
  Боль: 'Dolor',
  Одиночество: 'Soledad',
  Отчуждение: 'Alienación',
  Разочарование: 'Decepción',
  Поражение: 'Derrota',
  'Жалость к себе': 'Autocompasión',
  Тоска: 'Anhelo',
  Подавленность: 'Depresión',
  Предательство: 'Traición',
  Скука: 'Aburrimiento',
  Печаль: 'Tristeza',
  Апатия: 'Apatía',
  Примирение: 'Resignación',
  Отчаяние: 'Desesperación',
  Ущемлённость: 'Sentirse agraviado',

  Волнение: 'Agitación',
  Испуг: 'Susto',
  Паника: 'Pánico',
  Беспокойство: 'Preocupación',
  Неуверенность: 'Inseguridad',
  Боязливость: 'Timidez',
  Подозрительность: 'Sospecha',
  Трусость: 'Cobardía',
  Нерешительность: 'Indecisión',
  Настороженность: 'Cautela',
  Смятение: 'Confusión',
  Тревога: 'Ansiedad',
  Ужас: 'Terror',
  Опасение: 'Appréhension',
  Робость: 'Vergüenza',
  Застенчивость: 'Timidez',
  Безнадёжность: 'Desesperanza',
  Сдержанность: 'Reserva',
  Скрытность: 'Secretismo',
  Скованность: 'Tensión',
  Замешательство: 'Perplejidad',
  Ошарашенность: 'Estupefacción',
  Озадаченность: 'Desconcierto',

  Благодарность: 'Gratitud',
  Доверие: 'Confianza',
  Воодушевление: 'Inspiración',
  Озарение: 'Intuición',
  Сопричастность: 'Pertenencia',
  Умиротворение: 'Serenidad',
  Радушие: 'Calidez',
  Единство: 'Unidad',
  Торжественность: 'Solennité',
  Наслаждение: 'Plaisir',
  Общность: 'Comunidad',
  Восторг: 'Éxtasis',
  Благодать: 'Gracia',
  Поддержка: 'Apoyo',
  Весельe: 'Jovialidad',
  Надежда: 'Esperanza',
  Уверенность: 'Assurance',
  Лёгкость: 'Ligereza',
  Любовь: 'Amor',
  Удовлетворение: 'Satisfacción',
  Облегчение: 'Soulagement',
  Обожание: 'Adoración',
  Преклонение: 'Révérence',
  'Подъём духа': 'Ánimo',
  Энтузиазм: 'Entusiasmo',
};

// RU→FR
const RU_FR: Record<string, string> = {
  Холодность: 'Froideur',
  Злость: 'Colère',
  Бешенство: 'Fureur',
  Сарказм: 'Sarcasme',
  Раздражение: 'Irritation',
  Ярость: 'Rage',
  Унижение: 'Humiliation',
  Обида: 'Rancœur',
  Ненависть: 'Haine',
  Нетерпение: 'Impatience',
  Отвращение: 'Dégoût',
  Надменность: 'Arrogance',
  Злорадство: 'Joie malveillante',
  Недовольство: 'Mécontentement',
  Цинизм: 'Cynisme',
  Протест: 'Protestation',
  Неистовость: 'Frénésie',
  Враждебность: 'Hostilité',
  Равнодушие: 'Indifférence',
  Безучастность: 'Détachement',
  Неприязнь: 'Antipathie',
  Пренебрежение: 'Mépris',
  Зависть: 'Envie',
  Мстительность: 'Vengeance',
  Высокомерие: 'Suffisance',

  Вина: 'Culpabilité',
  Раскаяние: 'Remords',
  Нечестность: 'Malhonnêteté',
  'Угрызение совести': 'Scrupule',
  Стеснение: 'Pudeur',
  Неловкость: 'Malaise',
  Похоть: 'Luxure',
  Ущербность: 'Infériorité',
  Растерянность: 'Confusion',
  Обман: 'Tromperie',
  'Потеря лица': 'Perte de face',
  Смущение: 'Embarras',
  Позор: 'Déshonneur',
  Сожаление: 'Regret',
  Расщепление: 'Scission',
  Озабоченность: 'Préoccupation',
  Брошенность: 'Abandon',
  Замкнутость: 'Retrait',
  Угрюмость: 'Mauvaise humeur',
  Угнетённость: 'Abattement',
  Пассивность: 'Passivité',
  Отвержение: 'Rejet',

  Огорчение: 'Chagrin',
  Горе: 'Deuil',
  Боль: 'Douleur',
  Одиночество: 'Solitude',
  Отчуждение: 'Aliénation',
  Разочарование: 'Déception',
  Поражение: 'Défaite',
  'Жалость к себе': 'Auto-apitoiement',
  Тоска: 'Nostalgie',
  Подавленность: 'Dépression',
  Предательство: 'Trahison',
  Скука: 'Ennui',
  Печаль: 'Tristesse',
  Апатия: 'Apathie',
  Примирение: 'Résignation',
  Отчаяние: 'Désespoir',
  Ущемлённость: 'Se sentir lésé',

  Волнение: 'Agitation',
  Испуг: 'Frayeur',
  Паника: 'Panique',
  Беспокойство: 'Inquiétude',
  Неуверенность: 'Insécurité',
  Боязливость: 'Timidité',
  Подозрительность: 'Soupçon',
  Трусость: 'Lâcheté',
  Нерешительность: 'Indécision',
  Настороженность: 'Méfiance',
  Смятение: 'Trouble',
  Тревога: 'Anxiété',
  Ужас: 'Terreur',
  Опасение: 'Appréhension',
  Робость: 'Pudeur',
  Застенчивость: 'Timidité',
  Безнадёжность: 'Désespoir',
  Сдержанность: 'Réserve',
  Скрытность: 'Secret',
  Скованность: 'Raideur',
  Замешательство: 'Perplexité',
  Ошарашенность: 'Stupeur',
  Озадаченность: 'Désarroi',

  Благодарность: 'Gratitude',
  Доверие: 'Confiance',
  Воодушевление: 'Inspiration',
  Озарение: 'Illumination',
  Сопричастность: 'Appartenance',
  Умиротворение: 'Sérénité',
  Радушие: 'Chaleur',
  Единство: 'Unité',
  Торжественность: 'Solennité',
  Наслаждение: 'Plaisir',
  Общность: 'Communauté',
  Восторг: 'Ravissement',
  Благодать: 'Grâce',
  Поддержка: 'Soutien',
  Весельe: 'Allégresse',
  Надежда: 'Espoir',
  Уверенность: 'Assurance',
  Лёгкость: 'Légèreté',
  Любовь: 'Amour',
  Удовлетворение: 'Satisfaction',
  Облегчение: 'Soulagement',
  Обожание: 'Adoration',
  Преклонение: 'Révérence',
  'Подъём духа': 'Élan',
  Энтузиазм: 'Enthousiasme',
};

// RU→DE (немецкий)
const RU_DE: Record<string, string> = {
  Холодность: 'Kälte',
  Злость: 'Ärger',
  Бешенство: 'Wut',
  Сарказм: 'Sarkasmus',
  Раздражение: 'Reizung',
  Ярость: 'Raserei',
  Унижение: 'Demütigung',
  Обида: 'Kränkung',
  Ненависть: 'Hass',
  Нетерпение: 'Ungeduld',
  Отвращение: 'Ekel',
  Надменность: 'Arroganz',
  Злорадство: 'Schadenfreude',
  Недовольство: 'Unzufriedenheit',
  Цинизм: 'Zynismus',
  Протест: 'Protest',
  Неистовость: 'Raserei',
  Враждебность: 'Feindseligkeit',
  Равнодушие: 'Gleichgültigkeit',
  Безучастность: 'Distanziertheit',
  Неприязнь: 'Abneigung',
  Пренебрежение: 'Verachtung',
  Зависть: 'Neid',
  Мстительность: 'Rachsucht',
  Высокомерие: 'Hochmut',

  Вина: 'Schuld',
  Раскаяние: 'Reue',
  Нечестность: 'Unehrlichkeit',
  'Угрызение совести': 'Gewissensbiss',
  Стеснение: 'Schamhaftigkeit',
  Неловкость: 'Peinlichkeit',
  Похоть: 'Lust',
  Ущербность: 'Minderwertigkeit',
  Растерянность: 'Verwirrung',
  Обман: 'Betrug',
  'Потеря лица': 'Gesichtsverlust',
  Смущение: 'Verlegenheit',
  Позор: 'Schande',
  Сожаление: 'Bedauern',
  Расщепление: 'Spaltung',
  Озабоченность: 'Besorgnis',
  Брошенность: 'Verlassenheit',
  Замкнутость: 'Rückzug',
  Угрюмость: 'Übellaunigkeit',
  Угнетённость: 'Niedergeschlagenheit',
  Пассивность: 'Passivität',
  Отвержение: 'Zurückweisung',

  Огорчение: 'Verdruss',
  Горе: 'Trauer',
  Боль: 'Schmerz',
  Одиночество: 'Einsamkeit',
  Отчуждение: 'Entfremdung',
  Разочарование: 'Enttäuschung',
  Поражение: 'Niederlage',
  'Жалость к себе': 'Selbstmitleid',
  Тоска: 'Sehnsucht',
  Подавленность: 'Depression',
  Предательство: 'Verrat',
  Скука: 'Langeweile',
  Печаль: 'Traurigkeit',
  Апатия: 'Apathie',
  Примирение: 'Resignation',
  Отчаяние: 'Verzweiflung',
  Ущемлённость: 'Gekränktsein',

  Волнение: 'Aufregung',
  Испуг: 'Schreck',
  Паника: 'Panik',
  Беспокойство: 'Sorge',
  Неуверенность: 'Unsicherheit',
  Боязливость: 'Zaghaftigkeit',
  Подозрительность: 'Verdacht',
  Трусость: 'Feigheit',
  Нерешительность: 'Unentschlossenheit',
  Настороженность: 'Vorsicht',
  Смятение: 'Verwirrung',
  Тревога: 'Angst',
  Ужас: 'Schrecken',
  Опасение: 'Befürchtung',
  Робость: 'Schüchternheit',
  Застенчивость: 'Schüchternheit',
  Безнадёжность: 'Hoffnungslosigkeit',
  Сдержанность: 'Zurückhaltung',
  Скрытность: 'Geheimniskrämerei',
  Скованность: 'Gehemmtheit',
  Замешательство: 'Ratlosigkeit',
  Ошарашенность: 'Fassungslosigkeit',
  Озадаченность: 'Verblüffung',

  Благодарность: 'Dankbarkeit',
  Доверие: 'Vertrauen',
  Воодушевление: 'Inspiration',
  Озарение: 'Einsicht',
  Сопричастность: 'Zugehörigkeit',
  Умиротворение: 'Gelassenheit',
  Радушие: 'Herzlichkeit',
  Единство: 'Einheit',
  Торжественность: 'Feierlichkeit',
  Наслаждение: 'Vergnügen',
  Общность: 'Gemeinschaft',
  Восторг: 'Entzücken',
  Благодать: 'Gnade',
  Поддержка: 'Unterstützung',
  Весельe: 'Fröhlichkeit',
  Надежда: 'Hoffnung',
  Уверенность: 'Zuversicht',
  Лёгкость: 'Leichtigkeit',
  Любовь: 'Liebe',
  Удовлетворение: 'Zufriedenheit',
  Облегчение: 'Erleichterung',
  Обожание: 'Verehrung',
  Преклонение: 'Ehrfurcht',
  'Подъём духа': 'Aufschwung',
  Энтузиазм: 'Begeisterung',
};

// RU→ZH (китайский, упрощённый)
const RU_ZH: Record<string, string> = {
  Холодность: '冷漠',
  Злость: '愤怒',
  Бешенство: '狂怒',
  Сарказм: '讽刺',
  Раздражение: '恼怒',
  Ярость: '暴怒',
  Унижение: '屈辱',
  Обида: '受伤',
  Ненависть: '仇恨',
  Нетерпение: '不耐烦',
  Отвращение: '厌恶',
  Надменность: '傲慢',
  Злорадство: '幸灾乐祸',
  Недовольство: '不满',
  Цинизм: '犬儒',
  Протест: '抗议',
  Неистовость: '狂热',
  Враждебность: '敌意',
  Равнодушие: '冷淡',
  Безучастность: '疏离',
  Неприязнь: '反感',
  Пренебрежение: '轻蔑',
  Зависть: '嫉妒',
  Мстительность: '报复心',
  Высокомерие: '高傲',

  Вина: '内疚',
  Раскаяние: '懊悔',
  Нечестность: '不诚实',
  'Угрызение совести': '良心不安',
  Стеснение: '害羞',
  Неловкость: '尴尬',
  Похоть: '欲望',
  Ущербность: '自卑',
  Растерянность: '困惑',
  Обман: '欺骗',
  'Потеря лица': '丢脸',
  Смущение: '窘迫',
  Позор: '耻辱',
  Сожаление: '遗憾',
  Расщепление: '分裂',
  Озабоченность: '忧虑',
  Брошенность: '被抛弃',
  Замкнутость: '退缩',
  Угрюмость: '闷闷不乐',
  Угнетённость: '沮丧',
  Пассивность: '被动',
  Отвержение: '拒绝',

  Огорчение: '心烦',
  Горе: '悲痛',
  Боль: '痛苦',
  Одиночество: '孤独',
  Отчуждение: '疏离',
  Разочарование: '失望',
  Поражение: '失败',
  'Жалость к себе': '自怜',
  Тоска: '渴望',
  Подавленность: '抑郁',
  Предательство: '背叛',
  Скука: '无聊',
  Печаль: '悲伤',
  Апатия: '冷淡',
  Примирение: '认命',
  Отчаяние: '绝望',
  Ущемлённость: '受委屈',

  Волнение: '不安',
  Испуг: '惊吓',
  Паника: '恐慌',
  Беспокойство: '担忧',
  Неуверенность: '不安全感',
  Боязливость: '胆怯',
  Подозрительность: '怀疑',
  Трусость: '懦弱',
  Нерешительность: '优柔寡断',
  Настороженность: '警惕',
  Смятение: '混乱',
  Тревога: '焦虑',
  Ужас: '恐惧',
  Опасение: '担心',
  Робость: '害羞',
  Застенчивость: '害羞',
  Безнадёжность: '无望',
  Сдержанность: '克制',
  Скрытность: '保密',
  Скованность: '拘谨',
  Замешательство: '困惑',
  Ошарашенность: '震惊',
  Озадаченность: '迷惑',

  Благодарность: '感恩',
  Доверие: '信任',
  Воодушевление: '灵感',
  Озарение: '洞察',
  Сопричастность: '归属感',
  Умиротворение: '宁静',
  Радушие: '温暖',
  Единство: '团结',
  Торжественность: '庄严',
  Наслаждение: '快乐',
  Общность: '社群',
  Восторг: '喜悦',
  Благодать: '恩典',
  Поддержка: '支持',
  Веселье: '欢快',
  Надежда: '希望',
  Уверенность: '自信',
  Лёгкость: '轻松',
  Любовь: '爱',
  Удовлетворение: '满足',
  Облегчение: '释然',
  Обожание: '崇拜',
  Преклонение: '敬畏',
  'Подъём духа': '振奋',
  Энтузиазм: '热情',
};

function buildTranslations(ru: string): Record<Lang, string> {
  const en = RU_EN[ru] ?? ru;
  const es = RU_ES[ru] ?? en;
  const fr = RU_FR[ru] ?? en;
  const de = RU_DE[ru] ?? en;
  const zh = RU_ZH[ru] ?? en;
  return { ru, en, es, de, fr, zh };
}

function slugifyRu(input: string): string {
  const map: Record<string, string> = {
    а: 'a',
    б: 'b',
    в: 'v',
    г: 'g',
    д: 'd',
    е: 'e',
    ё: 'e',
    ж: 'zh',
    з: 'z',
    и: 'i',
    й: 'y',
    к: 'k',
    л: 'l',
    м: 'm',
    н: 'n',
    о: 'o',
    п: 'p',
    р: 'r',
    с: 's',
    т: 't',
    у: 'u',
    ф: 'f',
    х: 'h',
    ц: 'c',
    ч: 'ch',
    ш: 'sh',
    щ: 'shch',
    ь: '',
    ы: 'y',
    ъ: '',
    э: 'e',
    ю: 'yu',
    я: 'ya',
  };
  return input
    .toLowerCase()
    .replace(/ё/g, 'е')
    .replace(/[\s,.;:!?'"()\[\]{}]+/g, ' ')
    .trim()
    .split(' ')
    .map((word) =>
      word
        .split('')
        .map((ch) => map[ch] ?? ch)
        .join(''),
    )
    .join('_')
    .replace(/[^a-z0-9_]/g, '')
    .replace(/_+/g, '_');
}

function tdata(key: string, values: Partial<Record<Lang, string>>) {
  const langs: Lang[] = ['ru', 'en', 'es', 'de', 'fr', 'zh'];
  return langs.map((l) => ({
    languageCode: l,
    translationKey: key,
    translationValue: values[l] ?? values.ru ?? key,
  }));
}

async function main() {
  console.log('🌱 Seeding...');
  // Чистим только данные по эмоциям/категориям и их переводам
  await prisma.translation.deleteMany({
    where: { translationKey: { startsWith: 'emotion.' } },
  });
  await prisma.translation.deleteMany({
    where: { translationKey: { startsWith: 'emotion_category.' } },
  });
  await prisma.emotion.deleteMany();
  await prisma.emotionCategory.deleteMany();

  const cats = [
    {
      key: 'emotion_category.anger',
      ru: 'Гнев',
      en: 'Anger',
      es: 'Ira',
      de: 'Zorn',
      fr: 'Colère',
      zh: '愤怒',
      color: '#FF6B6B',
      icon: '😠',
      sort: 1,
    },
    {
      key: 'emotion_category.shame',
      ru: 'Стыд',
      en: 'Shame',
      es: 'Vergüenza',
      de: 'Scham',
      fr: 'Honte',
      zh: '羞耻',
      color: '#F59E0B',
      icon: '😳',
      sort: 2,
    },
    {
      key: 'emotion_category.sadness',
      ru: 'Грусть',
      en: 'Sadness',
      es: 'Tristeza',
      de: 'Traurigkeit',
      fr: 'Tristesse',
      zh: '悲伤',
      color: '#60A5FA',
      icon: '😢',
      sort: 3,
    },
    {
      key: 'emotion_category.fear',
      ru: 'Страх',
      en: 'Fear',
      es: 'Miedo',
      de: 'Angst',
      fr: 'Peur',
      zh: '恐惧',
      color: '#A78BFA',
      icon: '😰',
      sort: 4,
    },
    {
      key: 'emotion_category.joy',
      ru: 'Радость',
      en: 'Joy',
      es: 'Alegría',
      de: 'Freude',
      fr: 'Joie',
      zh: '喜悦',
      color: '#FCD34D',
      icon: '😊',
      sort: 5,
    },
  ];

  const createdCats = await Promise.all(
    cats.map((c) =>
      prisma.emotionCategory.create({
        data: {
          nameKey: c.key,
          color: c.color,
          icon: c.icon,
          sortOrder: c.sort,
          isActive: true,
        },
      }),
    ),
  );
  const catId: Record<string, number> = {};
  createdCats.forEach((c) => (catId[c.nameKey] = c.id));

  const angerRu = [
    'Холодность',
    'Злость',
    'Бешенство',
    'Сарказм',
    'Раздражение',
    'Ярость',
    'Унижение',
    'Обида',
    'Ненависть',
    'Нетерпение',
    'Отвращение',
    'Надменность',
    'Злорадство',
    'Недовольство',
    'Цинизм',
    'Протест',
    'Неистовость',
    'Враждебность',
    'Равнодушие',
    'Безучастность',
    'Неприязнь',
    'Пренебрежение',
    'Зависть',
    'Мстительность',
    'Высокомерие',
  ];
  const shameRu = [
    'Вина',
    'Раскаяние',
    'Унижение',
    'Нечестность',
    'Угрызение совести',
    'Стеснение',
    'Неловкость',
    'Похоть',
    'Ущербность',
    'Растерянность',
    'Обман',
    'Потеря лица',
    'Смущение',
    'Позор',
    'Сожаление',
    'Расщепление',
    'Озабоченность',
    'Брошенность',
    'Замкнутость',
    'Угрюмость',
    'Угнетённость',
    'Пассивность',
    'Отвержение',
  ];
  const sadnessRu = [
    'Огорчение',
    'Горе',
    'Боль',
    'Угнетённость',
    'Отвращение',
    'Одиночество',
    'Отчуждение',
    'Разочарование',
    'Поражение',
    'Жалость к себе',
    'Унижение',
    'Тоска',
    'Подавленность',
    'Предательство',
    'Скука',
    'Печаль',
    'Апатия',
    'Равнодушие',
    'Примирение',
    'Раздражение',
    'Обида',
    'Скорбь',
    'Отвержение',
    'Отчаяние',
    'Ущемлённость',
  ];
  const fearRu = [
    'Волнение',
    'Испуг',
    'Паника',
    'Беспокойство',
    'Неуверенность',
    'Боязливость',
    'Подозрительность',
    'Трусость',
    'Нерешительность',
    'Настороженность',
    'Смятение',
    'Тревога',
    'Ужас',
    'Опасение',
    'Робость',
    'Застенчивость',
    'Безнадёжность',
    'Сдержанность',
    'Скрытность',
    'Скованность',
    'Замешательство',
    'Ошарашенность',
    'Озадаченность',
  ];
  const joyRu = [
    'Благодарность',
    'Доверие',
    'Воодушевление',
    'Озарение',
    'Сопричастность',
    'Умиротворение',
    'Радушие',
    'Единство',
    'Торжественность',
    'Наслаждение',
    'Общность',
    'Восторг',
    'Благодать',
    'Поддержка',
    'Веселье',
    'Надежда',
    'Уверенность',
    'Лёгкость',
    'Любовь',
    'Удовлетворение',
    'Облегчение',
    'Обожание',
    'Преклонение',
    'Подъём духа',
    'Энтузиазм',
  ];

  const blocks = [
    { c: 'emotion_category.anger', list: angerRu, emoji: '😠' },
    { c: 'emotion_category.shame', list: shameRu, emoji: '😳' },
    { c: 'emotion_category.sadness', list: sadnessRu, emoji: '😢' },
    { c: 'emotion_category.fear', list: fearRu, emoji: '😰' },
    { c: 'emotion_category.joy', list: joyRu, emoji: '😊' },
  ];

  for (const c of cats) {
    await prisma.translation.createMany({
      data: tdata(c.key, {
        ru: c.ru,
        en: c.en,
        es: c.es,
        de: c.de,
        fr: c.fr,
        zh: c.zh,
      }),
      skipDuplicates: true,
    });
  }

  // Emotions + translations
  for (const b of blocks) {
    const cid = catId[b.c];
    const short = b.c.split('.')[1];
    for (let i = 0; i < b.list.length; i++) {
      const ru = b.list[i];
      const key = `emotion.${short}.${slugifyRu(ru)}`;
      await prisma.emotion.create({
        data: {
          categoryId: cid,
          nameKey: key,
          emoji: b.emoji,
          intensityDefault: 5,
          synonyms: [],
          sortOrder: i + 1,
          isActive: true,
        },
      });
      const vals = buildTranslations(ru);
      await prisma.translation.createMany({
        data: tdata(key, vals),
        skipDuplicates: true,
      });
    }
  }

  console.log('✅ Seeded categories and emotions (5 groups)');
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
